# vim: ft=ruby

# Core utilities and development tools
brew("age")
brew("stow")
brew("ansible")
brew("ansible-lint")
brew("bash")
brew("bat")
brew("bats-core")
brew("borgbackup")
brew("coreutils")
brew("curl")
brew("direnv")
brew("docker")
brew("docker-completion")
brew("docker-credential-helper")
brew("dust")
brew("et")
brew("exiftool")
brew("eza")
brew("fd")
brew("ffmpeg")
brew("fish")
brew("fisher")
brew("fselect")
brew("fzf")
brew("gh")
brew("git")
brew("git-lfs")
brew("gnu-sed")
brew("gnupg")
brew("go")
brew("grep")
brew("haskell-stack")
brew("hcloud")
brew("htop")
brew("httpie")
brew("hugo")
brew("jq")
brew("just")
brew("lazygit")
brew("llm")
brew("lsd")
brew("lsof")
brew("magic-wormhole")
brew("mas")
brew("n")
brew("ncspot")
brew("neovim")
brew("netcat")
brew("obfs4proxy")
brew("openai-whisper")
brew("openjdk")
brew("openssh")
brew("opentofu")
brew("packer")
brew("pandoc")
brew("pinentry-mac")
brew("proxychains-ng")
brew("python@3.12")
brew("python@3.13")
brew("pytorch")
brew("qemu")
brew("ranger")
brew("ripgrep")
brew("ripgrep-all")
brew("ruff")
brew("ruff-lsp")
brew("rust")
brew("rust-analyzer")
brew("sequoia-sq")
brew("sk")
brew("socat")
brew("ssh-askpass")
brew("sslscan")
brew("starship")
brew("streamlink")
brew("syncthing")
brew("tart")
brew("terraform")
brew("tesseract")
brew("tesseract-lang")
brew("tmux")
brew("tree-sitter")
brew("uniclip")
brew("usbutils")
brew("uutils-coreutils")
brew("uv")
brew("watch")
brew("wget")
brew("wireguard-go")
brew("wireguard-tools")
brew("xh")
brew("ykman")
brew("ykpers")
brew("yt-dlp")
brew("z")
brew("zoxide")
brew("zsync")

cask_args(appdir: "/Applications")

# Development applications
cask("android-platform-tools")
cask("balenaetcher")
cask("bitwarden")
cask("bricklink-studio")
cask("calibre")
cask("conductor")
cask("db-browser-for-sqlite")
cask("docker")
cask("docker-desktop")
cask("figma")
cask("flutter")
cask("gcloud-cli")
cask("ghostty")
cask("google-chrome")
cask("hammerspoon")
cask("keka")
cask("libreoffice")
cask("libreoffice-language-pack")
cask("lm-studio")
cask("microsoft-teams")
cask("mullvadvpn")
cask("nextcloud")
cask("ollama-app")
cask("paragon-ntfs")
cask("parsec")
cask("prusaslicer")
cask("qbittorrent")
cask("raycast")
cask("sidequest")
cask("superwhisper")
cask("thunderbird")
cask("utm")
cask("vagrant")
cask("visual-studio-code")
cask("visual-studio-code@insiders")
cask("vivaldi")
cask("whatsapp")
cask("yubico-yubikey-manager")
cask("zed")
cask("zoom")
cask("zotero")

# Fonts
cask("font-cascadia-code-nf")
cask("font-cascadia-mono-nf")

# Mac App Store applications
mas("Bitwarden", id: 1352778147)
mas("Connecton", id: 1497000705)
mas("CrystalFetch", id: 6454431289)
mas("Enchanted", id: 6474268307)
mas("GarageBand", id: 682658836)
mas("iMovie", id: 408981434)
mas("Keynote", id: 409183694)
mas("Microsoft Remote Desktop", id: 1295203466)
mas("NextDNS", id: 1464122853)
mas("Numbers", id: 409203825)
mas("Pages", id: 409201541)
mas("Toggl Track", id: 1291898086)
mas("uBlock Origin Lite", id: 6745342698)
mas("Unzip - RAR ZIP 7Z Unarchiver", id: 1537056818)
mas("WireGuard", id: 1451685025)
mas("Xcode", id: 497799835)