keys:
  - &mi-skam age16uelq9w6kw6wt0e5srm3vu8nsf0zqjkc9esdv4mynslf0quw93vqdp2ksj
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *mi-skam
  - path_regex: secrets/.*\.json$
    key_groups:
      - age:
          - *mi-skam
