---
# Monitoring role handlers

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: Restart promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted
    daemon_reload: true
