---
- name: Setup Hetzner Storage Box mounting
  hosts: all
  become: yes

  tasks:
    - name: Load SOPS encrypted secrets
      community.sops.load_vars:
        file: ../../secrets/storagebox.yaml
      delegate_to: localhost

    - name: Set storagebox variables
      ansible.builtin.set_fact:
        storagebox_username: "{{ storagebox.username }}"
        storagebox_password: "{{ storagebox.password }}"
        storagebox_host: "{{ storagebox.host }}"

    - name: Include storagebox role
      ansible.builtin.include_role:
        name: storagebox
